### ISSUE TITLE
Adding Points to a Polygon

### ISSUE THREAD

**Issue by NyxCode** [bodoni/svg#18]
Sadly, there is no documentation for any of the types in `node::element` since most of the methods seem to be generated by macros.. Because of this, it seems to by impossible to use this library without diving into the source and deciphering the macros..

My specific question: How would I use the `Polygon` type? How do I add points to a polygon?

**Comment by NyxCode** [comment]
hm, i guess `Polygon::new().set("points", "0,0 0,20 20,20 .......")` works..

**Comment by IvanUkhov** [comment]
Thank for the issue! Right, I just want to make a parallel with the `Path` element. For that element, there is an auxiliary structure provided, called `Data`, that is dedicated to creating the `d` attribute (_d_ for _data_) of this element. One can image that for `Polygon` one might also want to have such an auxiliary structure with a similar interface in order to make it more convenient.
